// Generates supabase/seed.sql from the app's seed products, scoring them with the same code the app uses.
import { writeFileSync } from 'node:fs';
import { seedProducts } from '../app/src/data/seed';
import { scoreProduct } from '../app/src/scoring';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = ['-- generated by scripts/gen-seed.ts; fake products only', 'begin;'];
const ing = new Map<string, { kind: string; risk: string; note?: string }>();
for (const p of seedProducts) for (const i of p.ingredients) {
  ing.set(`${p.type === 'food' ? 'additive' : 'cosmetic'}|${i.name}`, { kind: p.type === 'food' ? 'additive' : 'cosmetic', risk: i.risk, note: i.note });
}
for (const [k, v] of ing) {
  const name = k.split('|')[1];
  out.push(`insert into ingredients (kind, name, risk_level, note) values (${q(v.kind)}, ${q(name)}, ${q(v.risk)}, ${v.note ? q(v.note) : 'null'}) on conflict (kind, name) do nothing;`);
}
for (const p of seedProducts) {
  const r = scoreProduct(p);
  const n = p.nutrition ? q(JSON.stringify(p.nutrition)) + '::jsonb' : "'{}'::jsonb";
  out.push(`insert into products (barcode, type, name, brand, category, organic, nutrition, tags, source, score, color) values (${q(p.barcode)}, ${q(p.type)}, ${q(p.name)}, ${q(p.brand)}, ${q(p.category)}, ${p.organic}, ${n}, array[${p.tags.map(q).join(',')}]::text[], 'manual', ${r.score}, ${q(r.color)}) on conflict (barcode) do nothing;`);
  p.ingredients.forEach((i, idx) => {
    const kind = p.type === 'food' ? 'additive' : 'cosmetic';
    out.push(`insert into product_ingredients select p.id, i.id, ${idx} from products p, ingredients i where p.barcode = ${q(p.barcode)} and i.kind = ${q(kind)} and i.name = ${q(i.name)} on conflict do nothing;`);
  });
}
out.push('commit;');
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log(`seed.sql: ${seedProducts.length} products, ${ing.size} ingredients`);
